# Generated by Django 5.0.6 on 2024-07-08 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default=None, max_length=15)),
                ('lastName', models.CharField(default=None, max_length=15)),
                ('email', models.EmailField(default=None, max_length=30, unique=True)),
                ('password', models.CharField(default=None, max_length=200)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('owner', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('orgId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default=None, max_length=200)),
                ('users', models.ManyToManyField(related_name='User', to='auth_api.user')),
            ],
        ),
    ]
