# Generated by Django 5.0.6 on 2024-07-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_Id',
            new_name='userId',
        ),
    ]
